---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	initialize_state(initialize_state)
	ticket_analyzer(ticket_analyzer)
	retrieval_agent(retrieval_agent)
	diagnosis_agent(diagnosis_agent)
	resolution_agent(resolution_agent)
	verification_agent(verification_agent)
	decision_agent(decision_agent)
	auto_resolve(auto_resolve)
	human_review(human_review)
	escalate(escalate)
	__end__([<p>__end__</p>]):::last
	__start__ --> initialize_state;
	decision_agent -.-> auto_resolve;
	decision_agent -.-> escalate;
	decision_agent -.-> human_review;
	diagnosis_agent --> resolution_agent;
	initialize_state --> ticket_analyzer;
	resolution_agent --> verification_agent;
	retrieval_agent --> diagnosis_agent;
	ticket_analyzer --> retrieval_agent;
	verification_agent --> decision_agent;
	auto_resolve --> __end__;
	escalate --> __end__;
	human_review --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
